# Generated by Django 3.2.21 on 2024-01-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='letting',
        #     name='address',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.RemoveField(
            model_name='letting',
            name='address',
            ),
            ],
            database_operations=[],
        ),
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
            migrations.RemoveField(
            model_name='profile',
            name='user',
            ),
            ],
            database_operations=[],
        ),
        # migrations.DeleteModel(
        #     name='Address',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Address',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Address',
                    table='lettings_address',
                ),
            ],
            ),
        # migrations.DeleteModel(
        #     name='Letting',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Letting',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Letting',
                    table='lettings_letting',
                ),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Profile',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Profile',
                    table='profiles_profile',
                ),
            ],
        ),
    ]
